<?php
/* @var $helper Mage_Adminhtml_Helper_Data */
$helper = $this->helper('adminhtml');
?>
<script>
    var baseConfirmKeyUrl  = "<?php echo $helper->getUrl("adminhtml/crconfig/confirmKey")?>";
    var baseChangeGroupUrl = "<?php echo $helper->getUrl("adminhtml/crconfig/changeGroup")?>";
    var baseGroupsBlockUrl = "<?php echo $helper->getUrl("adminhtml/crconfig/getGroupsBlock")?>";
    var savedDefaultListId = "<?php echo Mage::helper("crconnect")->getDefaultListId();?>";
    var savedDefaultFormId = "<?php echo Mage::helper("crconnect")->getDefaultFormId();?>";
    var savedFormsKeys = new Array();
    <?php foreach (Mage::helper("crconnect")->getFormsIdsByKeys() as $key=>$formKey):?>
    savedFormsKeys[<?php echo "'" . $key . "'";?>] = "<?php echo $formKey;?>";
    <?php endforeach;?>

    var crconnectLang = new Array();
    crconnectLang['please:select:group:default'] = "<?php echo Mage::helper("crconnect")->__("No groups to select")?>";
    crconnectLang['please:select:form:default'] = "<?php echo Mage::helper("crconnect")->__("No forms to select")?>";
    crconnectLang['please:select:group'] = "<?php echo Mage::helper("crconnect")->__("Please select subscribers group")?>";
    crconnectLang['please:select:form'] = "<?php echo Mage::helper("crconnect")->__("Please select form")?>";

</script>
